schema = 3

[mod]
  [mod."github.com/bmatcuk/doublestar/v4"]
    version = "v4.2.0"
    hash = "sha256-7xnw1NxJQhpCrOiWOxIgpztSFAgsRJu2w1xlbRR3Tac="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.8"
    hash = "sha256-8zkIo+Sr1NXMnj3PNmvjX2sZKnAKWXOFvmnX7D9bwxQ="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
